version: '3.7'
services:
  mysqldb:
    image: mysql:8.0.33
    ports:
      - 3306:3306
    environment:
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_ROOT_PASSWORD=${MYSQL_PASSWORD}
    volumes:
      - carpark-mysql-data:/var/lib/mysql
    networks:
      - carpark-network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-p$$MYSQL_PASSWORD","--protocol","tcp"]
      retries: 10
      interval: 3s
      timeout: 30s
  carpark:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8090:8090
    depends_on:
      wait-for-db:
        condition: service_completed_successfully
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysqldb:3306/${MYSQL_DATABASE}
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=${MYSQL_PASSWORD}
    networks:
      - carpark-network
  wait-for-db:
    image: atkrad/wait4x
    depends_on:
      - mysqldb
    command: tcp mysqldb:3306 -t 300s -i 250ms
    networks:
      - carpark-network
volumes:
  carpark-mysql-data:
networks:
  carpark-network:
    name: carpark-network
